redirect-path: '/tutorial/install-mongodb-on-amazon-ec2'
url-base: '/platforms/amazon-ec2'
type: 'redirect'
code: 301
outputs:
  - 'ecosystem'
---
redirect-path: '/tutorial/automate-deployment-with-cloudformation'
url-base: '/platforms/amazon-ec2'
type: 'redirect'
code: 301
outputs:
  - 'ecosystem'
---
redirect-path: '/tutorial/deploy-mongodb-from-aws-marketplace'
url-base: '/platforms/amazon-ec2'
type: 'redirect'
code: 301
outputs:
  - 'ecosystem'
---
redirect-path: '/tutorial/install-mongodb-on-windows-azure'
url-base: '/platforms/windows-azure'
type: 'redirect'
code: 301
outputs:
  - 'ecosystem'
---
redirect-path: '/tutorials'
url-base: '/tutorial'
type: 'redirect'
code: 303
outputs:
  - 'ecosystem'
---
from: '/drivers/cpp'
to: '/wiki'
code: 303
external: 'https://github.com/mongodb/mongo-cxx-driver'
outputs: ['ecosystem']
---
from: '/tutorial/download-and-compile-cpp-driver'
to: '/Download%20and%20Compile'
code: 303
external: 'https://github.com/mongodb/mongo-cxx-driver/wiki'
outputs: ['ecosystem']
---
from: '/tutorial/getting-started-with-cpp-driver'
to: '/blob/legacy/README.md'
code: 303
external: 'https://github.com/mongodb/mongo-cxx-driver'
outputs: ['ecosystem']
---
from: '/drivers/cpp-bson-array-examples'
to: '/blob/legacy/src/mongo/client/examples/arrayExample.cpp'
code: 303
external: 'https://github.com/mongodb/mongo-cxx-driver'
outputs: ['ecosystem']
---
from: "/drivers/cpp-bson-helper-functions"
to: "/BSON Helper Functions"
code: 303
external: 'https://github.com/mongodb/mongo-cxx-driver/wiki'
outputs: ['ecosystem']
...