project: 'mongodb-ecosystem'
master_doc: 'contents'
paths:
  static: ['source/.static']
theme:
  name: 'ecosystem'
  sitename: 'MongoDB Ecosystem'
  jira: 'DOCS'
  google_analytics: 'UA-7301842-8'
sidebars:
  '**':
    - 'pagenav.html'
...